project:
  type: website
  output-dir: docs

website:
  title: "data-stories"
  comments: 
    utterances: 
       repo: toduor/datastories-blog-posts
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css



